### ISSUE TITLE
Variable scope Dashboards

### ISSUE THREAD

**Issue by alketshabani** [sysdiglabs/sysdig-sdk-python#121]
Hello,
is there a way to create a dashboards scope without being defined, meaning:

kubernetes.namespace.name in (var)

Thanks

**Comment by tembleking** [comment]
Hi @alketshabani, do you mean with `kubernetes.namespace.name` not being defined in your environment, or with `var` not being defined?

If the `kubernetes.namespace.name` does not exist in your environment, because you never had a Kubernetes cluster being monitored, then you cannot create this scope. 
The `var` is not evaluated when creating scopes, it's just used during the usage of the dashboard, so if the `kubernetes.namespace.name` scope exists in your environment, then you can create `kubernetes.namespace.name in (var)` even if you don't have a `var` namespace.

I will close this issue, if you have any other doubt, please don't hesitate to open it again.
Thanks!
